export const PLAYER_MOVE_SPEED = 0.1
export const PLAYER_RADIUS = 32
export const PLAYER_COLLISION_LENIENCY = PLAYER_RADIUS / 4
export const POSITION_UPDATE_TIME = 25
export const BULLET_SPEED = 0.5
export const BULLET_RADIUS = 5
export const WALL_THICKNESS = 20
export const NAME_HEIGHT_ABOVE_PLAYER = 75
export const GUN_LENGTH = 60
export const GUN_WIDTH = 14
export const OUTLINE_COLOR = '#272736'
export const TIME_BETWEEN_SHOTS_MS = 200
