app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/raghavio
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool-size: 30
spring:
  flyway:
    baseline-on-migrate: true
